version: '3.8'

services:
  # MongoDB service
  mongo:
    image: mongo:6
    container_name: blogsink-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-rootpassword}
    networks:
      - blogsink-network

  # Backend API service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: blogsink-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME:-root}:${MONGO_INITDB_ROOT_PASSWORD:-rootpassword}@mongo:27017/blogsink?authSource=admin
      - JWT_SECRET=${JWT_SECRET:-defaultsecret}
      - JWT_EXPIRE=${JWT_EXPIRE:-30d}
      - JWT_COOKIE_EXPIRE=${JWT_COOKIE_EXPIRE:-30}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_EMAIL=${SMTP_EMAIL}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - FROM_EMAIL=${FROM_EMAIL:-noreply@blogsink.com}
      - FROM_NAME=${FROM_NAME:-BlogsInk}
    volumes:
      - ./backend/uploads:/usr/src/app/uploads
    networks:
      - blogsink-network

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: blogsink-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    networks:
      - blogsink-network

volumes:
  mongo-data:
    driver: local

networks:
  blogsink-network:
    driver: bridge